services:
  books-app:
    container_name: books-app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./books:/books
    environment:
      - DB_HOST=dbooks
      - DB_NAME=books_db
      - DB_USER=books_user
      - DB_PASS=12pass345
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - dbooks

  dbooks:
    image: postgres:14.6-alpine
    #restart: always
    environment:
      - POSTGRES_DB=books_db
      - POSTGRES_USER=books_user
      - POSTGRES_PASSWORD=12pass345
    ports:
    -   5433:5432